#!/bin/bash

echo "=== Plugin Marketplace 下载脚本 ==="
echo ""
echo "项目结构："
echo "├── backend/     # Express + TypeORM + PostgreSQL API"
echo "├── frontend/    # Vue.js 市场界面"
echo "├── publisher/   # Vue.js 发布者仪表板"
echo "├── README.md    # 详细文档"
echo "└── package.json # 根目录配置"
echo ""
echo "压缩包大小：382KB"
echo "包含所有源代码，排除 node_modules"
echo ""
echo "下载命令："
echo "wget http://your-server/plugin-marketplace.tar.gz"
echo ""
echo "解压命令："
echo "tar -xzf plugin-marketplace.tar.gz"
echo ""
echo "安装依赖："
echo "npm run install:all"
echo ""
echo "启动项目："
echo "npm run dev:all"
echo ""
echo "端口配置："
echo "- Backend API: http://localhost:3000"
echo "- Frontend: http://localhost:3001"
echo "- Publisher: http://localhost:3002"
echo ""
echo "数据库配置："
echo "请先配置 PostgreSQL 并创建数据库："
echo "CREATE DATABASE plugin_marketplace;"
echo ""
echo "然后配置 .env 文件："
echo "DATABASE_URL=postgresql://postgres:password@localhost:5432/plugin_marketplace"
echo ""